export type Locale = 'uk' | 'en';
export const defaultLocale: Locale = 'uk';

export const translations = {
  uk: {
    common: { language: 'Мова', ukrainian: 'Українська', english: 'English' },
    nav: { dashboard: 'Головна', leads: 'Ліди', companies: 'Компанії', contacts: 'Контакти', activities: 'Активності', reports: 'Звіти', settings: 'Налаштування' },
    crm: { newLead: 'Новий лід', searchLeads: 'Пошук лідів...', totalLeads: 'Всього лідів', new: 'Нові', synced: 'Синхронізовані', failed: 'Помилки', name: 'Імʼя', company: 'Компанія', email: 'Email', message: 'Повідомлення', noCompany: 'Без компанії', edit: 'Редагувати', save: 'Зберегти', cancel: 'Скасувати', archive: 'Архівувати', back: 'Назад', status: 'Статус', flectraLeadId: 'Flectra Lead ID', checkApi: 'Перевірити API', checkFlectra: 'Перевірити Flectra', connected: 'Підключено', offline: 'Недоступно', checking: 'Перевірка...', noSyncedLeads: 'Немає синхронізованих лідів', apiError: 'Помилка API', created: 'Створено', updated: 'Оновлено', archiveConfirm: 'Ви впевнені, що хочете архівувати цей лід?', archived: 'Архівовано', all: 'Всі', noLeads: 'Лідів поки немає', loading: 'Завантаження...', error: 'Помилка', retry: 'Повторити', create: 'Створити', creating: 'Створення...', saving: 'Збереження...', editLead: 'Редагувати лід', newLeadTitle: 'Новий лід', leadDetails: 'Деталі ліда', createdAt: 'Створено', updatedAt: 'Оновлено', search: 'Пошук', clear: 'Очистити', dashboardTitle: 'Головна', dashboardDescription: 'Огляд вашої CRM-воронки', totalLeadsCard: 'Всього лідів', newLeadsCard: 'Нові ліди', contactsTitle: 'Контакти', contactsDescription: 'Контакти з ваших лідів', searchContacts: 'Пошук контактів...', lastLead: 'Останній лід', reportsTitle: 'Звіти', reportsDescription: 'Огляд ефективності CRM', topCompanies: 'Топ компаній', leadsCount: 'лідів', settingsTitle: 'Налаштування', settingsDescription: 'Конфігурація CRM та системна інформація', system: 'Система', leadSynchronization: 'Синхронізація лідів', flectraViaWorker: 'Flectra через Outbox Worker', pipeline: 'Воронка', leadsCountShort: 'лідів', createLead: 'Створити лід', createNewLead: 'Створити новий лід', updateLead: 'Оновити інформацію про лід', saveChanges: 'Зберегти зміни', messageMin: 'Повідомлення (мін. 10 символів)', notSynced: 'Не синхронізовано', unexpectedResponse: 'Неочікувана відповідь API', failedLoad: 'Не вдалося завантажити ліди', failedCreate: 'Не вдалося створити лід', failedUpdate: 'Не вдалося оновити лід', failedArchive: 'Не вдалося архівувати лід', leadUpdated: 'Лід оновлено', leadCreated: 'Лід створено', newStatus: 'Нові', syncedStatus: 'Синхронізовані', failedStatus: 'Помилки', nameUpper: 'ІМʼЯ', emailUpper: 'EMAIL', companyUpper: 'КОМПАНІЯ', lastLeadUpper: 'ОСТАННІЙ ЛІД', statusUpper: 'СТАТУС', flectraIdUpper: 'FLECTRA LEAD ID', messageUpper: 'ПОВІДОМЛЕННЯ', adminUser: 'Admin User' },
    website: { consultingPoc: 'Consulting POC', heroTitle: 'Консалтинг, який починається зі слухання.', heroDescription: 'Це технічний proof of concept: контактна форма спочатку записує дані у нашу базу, а потім передає їх до CRM через backend worker — сайт не залежить від доступності CRM.', startConversation: 'Почати розмову', contact: 'Контакти', contactUs: 'Звʼяжіться з нами', contactDescription: 'Коротко розкажіть, з чим вам потрібна допомога. Ваше повідомлення спочатку зберігається у наших системах, а потім передається до CRM — ніколи навпаки.' }
  },
  en: {
    common: { language: 'Language', ukrainian: 'Українська', english: 'English' },
    nav: { dashboard: 'Dashboard', leads: 'Leads', companies: 'Companies', contacts: 'Contacts', activities: 'Activities', reports: 'Reports', settings: 'Settings' },
    crm: { newLead: 'New Lead', searchLeads: 'Search leads...', totalLeads: 'Total Leads', new: 'New', synced: 'Synced', failed: 'Failed', name: 'Name', company: 'Company', email: 'Email', message: 'Message', noCompany: 'No company', edit: 'Edit', save: 'Save', cancel: 'Cancel', archive: 'Archive', back: 'Back', status: 'Status', flectraLeadId: 'Flectra Lead ID', checkApi: 'Check API', checkFlectra: 'Check Flectra', connected: 'Connected', offline: 'Offline', checking: 'Checking...', noSyncedLeads: 'No synced leads', apiError: 'API error', created: 'Created', updated: 'Updated', archiveConfirm: 'Are you sure you want to archive this lead?', archived: 'Archived', all: 'All', noLeads: 'No leads yet', loading: 'Loading...', error: 'Error', retry: 'Retry', create: 'Create', creating: 'Creating...', saving: 'Saving...', editLead: 'Edit lead', newLeadTitle: 'New lead', leadDetails: 'Lead details', createdAt: 'Created', updatedAt: 'Updated', search: 'Search', clear: 'Clear', dashboardTitle: 'Dashboard', dashboardDescription: 'Overview of your CRM pipeline', totalLeadsCard: 'Total Leads', newLeadsCard: 'New Leads', contactsTitle: 'Contacts', contactsDescription: 'Contacts from your leads', searchContacts: 'Search contacts...', lastLead: 'Last Lead', reportsTitle: 'Reports', reportsDescription: 'CRM performance overview', topCompanies: 'Top Companies', leadsCount: 'leads', settingsTitle: 'Settings', settingsDescription: 'CRM configuration and system information', system: 'System', leadSynchronization: 'Lead synchronization', flectraViaWorker: 'Flectra via Outbox Worker', pipeline: 'Pipeline', leadsCountShort: 'leads', createLead: 'Create Lead', createNewLead: 'Create a new lead', updateLead: 'Update lead information', saveChanges: 'Save Changes', messageMin: 'Message (min. 10 characters)', notSynced: 'Not synced', unexpectedResponse: 'Unexpected API response', failedLoad: 'Failed to load leads', failedCreate: 'Failed to create lead', failedUpdate: 'Failed to update lead', failedArchive: 'Failed to archive lead', leadUpdated: 'Lead updated', leadCreated: 'Lead created', newStatus: 'New', syncedStatus: 'Synced', failedStatus: 'Failed', nameUpper: 'NAME', emailUpper: 'EMAIL', companyUpper: 'COMPANY', lastLeadUpper: 'LAST LEAD', statusUpper: 'STATUS', flectraIdUpper: 'FLECTRA LEAD ID', messageUpper: 'MESSAGE', adminUser: 'Admin User' },
    website: { consultingPoc: 'Consulting POC', heroTitle: 'Consulting that starts with listening.', heroDescription: 'This is the technical proof of concept: the contact form writes to our own database and is handed to the CRM by our backend worker — the website never depends on the CRM being available.', startConversation: 'Start a conversation', contact: 'Contact', contactUs: 'Contact us', contactDescription: 'Tell us briefly what you need help with. Your message is stored in our own systems first and then passed to our CRM — never the other way around.' }
  }
} as const;

export type Translations = (typeof translations)[Locale];

export function getTranslations(locale: Locale): Translations {
  return translations[locale];
}




